# zcode-shield one-shot setup for Windows (run in normal PowerShell; tasks run as current user).
# 1) locates or installs mitmproxy (winget)
# 2) copies project files to the install dir
# 3) registers the resident mitmdump task + the 30s monitor task
# 4) prints verification / next-step instructions.
param(
  [int]$ProxyPort = 18080,
  [string]$InstallDir = "$env:USERPROFILE\.zcode-shield"
)
$ErrorActionPreference = 'Stop'

# Refresh this session's PATH from the registry: installs made after this
# window was opened (e.g. a just-finished winget install) are otherwise
# invisible to Get-Command until a new process starts.
function Update-SessionPath {
  $userPath = [Environment]::GetEnvironmentVariable('Path', 'User')
  $machinePath = [Environment]::GetEnvironmentVariable('Path', 'Machine')
  $env:PATH = "$userPath;$machinePath;$env:PATH"
}

# Locate mitmdump.exe without assuming one fixed install location.
# Covers: PATH (after registry refresh), winget/pyinstaller user & machine
# layouts (both "<dir>\mitmdump.exe" and "<dir>\bin\mitmdump.exe"), scoop,
# pipx/pip --user, and custom dirs recorded in the uninstall registry.
function Find-Mitmdump {
  $cmd = Get-Command mitmdump -ErrorAction SilentlyContinue
  if ($cmd) { return $cmd.Source }

  $roots = @(
    "$env:LOCALAPPDATA\Programs\mitmproxy",
    "$env:ProgramFiles\mitmproxy",
    "${env:ProgramFiles(x86)}\mitmproxy",
    "$env:USERPROFILE\scoop\shims",
    "$env:USERPROFILE\.local\bin"
  ) | Where-Object { $_ }
  foreach ($root in $roots) {
    foreach ($exe in @((Join-Path $root 'mitmdump.exe'), (Join-Path $root 'bin\mitmdump.exe'))) {
      if (Test-Path $exe) { return $exe }
    }
  }

  $uninstallKeys = @(
    'HKCU:\Software\Microsoft\Windows\CurrentVersion\Uninstall\*',
    'HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall\*',
    'HKLM:\Software\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\*'
  )
  $locations = Get-ItemProperty $uninstallKeys -ErrorAction SilentlyContinue |
    Where-Object { $_.DisplayName -like '*mitmproxy*' -and $_.InstallLocation } |
    Select-Object -ExpandProperty InstallLocation -Unique
  foreach ($loc in $locations) {
    foreach ($exe in @((Join-Path $loc 'mitmdump.exe'), (Join-Path $loc 'bin\mitmdump.exe'))) {
      if (Test-Path $exe) { return $exe }
    }
  }
  return $null
}

# --- mitmproxy ---
Update-SessionPath
$mitmdump = Find-Mitmdump
if (-not $mitmdump) {
  Write-Host "[*] mitmproxy not found, installing via winget..."
  if (-not (Get-Command winget -ErrorAction SilentlyContinue)) {
    throw "winget not available and mitmdump.exe not found. Install mitmproxy manually (https://mitmproxy.org, or 'pipx install mitmproxy') and re-run this script."
  }
  winget install --id mitmproxy.mitmproxy -e --accept-source-agreements --accept-package-agreements
  Update-SessionPath
  $mitmdump = Find-Mitmdump
}
if (-not $mitmdump) {
  throw @(
    "mitmdump.exe still not found after install attempt. Searched: PATH (user+machine registry),"
    "%LOCALAPPDATA%\Programs\mitmproxy, %ProgramFiles%\mitmproxy, scoop shims, pip --user, uninstall registry."
    "Install manually from https://mitmproxy.org (or 'pipx install mitmproxy'), open a NEW PowerShell window, and re-run."
  ) -join ' '
}
Write-Host "[*] mitmdump: $mitmdump"

# --- copy project files into the install dir (always refresh) ---
$repoRoot = Split-Path -Parent $PSScriptRoot
New-Item -ItemType Directory -Force -Path $InstallDir | Out-Null
Copy-Item -Force "$repoRoot\mitm-addon.py" "$InstallDir\mitm-addon.py"
foreach ($f in 'ZcodeSnapshotWatch.ps1', 'enable-proxy.ps1', 'disable-proxy.ps1',
              'enable-proxy.cmd', 'disable-proxy.cmd') {
  Copy-Item -Force "$PSScriptRoot\$f" "$InstallDir\$f"
}
Write-Host "[*] installed to: $InstallDir"

# --- generate launchers so tasks never flash a console window ---
# Task Scheduler running a console binary (powershell.exe/mitmdump.exe) creates
# a visible console even with -WindowStyle Hidden (brief flash). wscript.exe is
# a GUI-subsystem binary and WshShell.Run with window style 0 creates the child
# console hidden from the start - zero flash. The mitm launcher uses
# bWaitOnReturn=True and propagates the exit code, so Task Scheduler's
# RestartCount still fires when mitmdump crashes.
$wscript = Join-Path $env:WINDIR 'System32\wscript.exe'
$useVbs = Test-Path $wscript

$runMitmPs1 = @"
# Generated by setup-zcode-shield.ps1 - the actual mitmdump command line for this machine.
# exit `$LASTEXITCODE propagates mitmdump's exit code so Task Scheduler sees a
# failed task (and so the monitor's watchdog can restart it).
`$env:ZCODE_SHIELD_DIR = "$InstallDir"
& "$mitmdump" -s "$InstallDir\mitm-addon.py" --listen-host 127.0.0.1 --listen-port $ProxyPort --set connection_strategy=lazy *>> "$InstallDir\mitmdump.log"
exit `$LASTEXITCODE
"@
[System.IO.File]::WriteAllText("$InstallDir\run-mitm.ps1", $runMitmPs1, (New-Object System.Text.UTF8Encoding $true))

if ($useVbs) {
  # In VBS string literals a double quote is escaped as "" - kept literal via
  # single-quoted here-strings, then placeholders are replaced per machine.
  $mitmVbs = @'
' zcode-shield launcher (generated) - window style 0: fully hidden, no console flash.
' Wait=True keeps wscript alive so the task restarts mitmdump on non-zero exit.
' Process launches can be canceled during early logon (0x800704C7
' ERROR_CANCELLED) while the session is still initializing; retry silently.
' The unguarded final Run only surfaces the WSH error popup - the user alert -
' after every retry has failed, i.e. for persistent failures, not logon races.
Dim sh : Set sh = CreateObject("WScript.Shell")
Dim cmd : cmd = "powershell.exe -NoProfile -ExecutionPolicy Bypass -File ""__RUN__"""
Dim rc, i
On Error Resume Next
For i = 1 To 6
  Err.Clear
  rc = sh.Run(cmd, 0, True)
  If Err.Number = 0 Then WScript.Quit rc
  WScript.Sleep 10000
Next
On Error GoTo 0
WScript.Quit sh.Run(cmd, 0, True)
'@
  $watchVbs = @'
' zcode-shield launcher (generated) - window style 0: fully hidden, no console flash.
CreateObject("WScript.Shell").Run "powershell.exe -NoProfile -ExecutionPolicy Bypass -File ""__WATCH__"" -ShieldDir ""__DIR__""", 0, False
'@
  $mitmVbs = $mitmVbs.Replace('__RUN__', "$InstallDir\run-mitm.ps1")
  $watchVbs = $watchVbs.Replace('__WATCH__', "$InstallDir\ZcodeSnapshotWatch.ps1").Replace('__DIR__', $InstallDir)
  # UTF-16 with BOM: WSH reads Unicode .vbs, so non-ASCII install paths stay intact.
  [System.IO.File]::WriteAllText("$InstallDir\run-mitm.vbs", $mitmVbs, [System.Text.Encoding]::Unicode)
  [System.IO.File]::WriteAllText("$InstallDir\run-watch.vbs", $watchVbs, [System.Text.Encoding]::Unicode)

  $mitAction = New-ScheduledTaskAction -Execute $wscript -Argument "`"$InstallDir\run-mitm.vbs`""
  $watchAction = New-ScheduledTaskAction -Execute $wscript -Argument "`"$InstallDir\run-watch.vbs`""
} else {
  Write-Warning "wscript.exe not found - falling back to powershell -WindowStyle Hidden (each task run will briefly flash a console window)"
  $mitmCommand = "`$env:ZCODE_SHIELD_DIR = '$InstallDir'; & '$mitmdump' -s '$InstallDir\mitm-addon.py' --listen-host 127.0.0.1 --listen-port $ProxyPort --set connection_strategy=lazy *>> '$InstallDir\mitmdump.log'; exit `$LASTEXITCODE"
  $mitAction = New-ScheduledTaskAction -Execute 'powershell.exe' `
    -Argument "-NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -Command `"$mitmCommand`""
  $watchAction = New-ScheduledTaskAction -Execute 'powershell.exe' `
    -Argument "-NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -File `"$InstallDir\ZcodeSnapshotWatch.ps1`" -ShieldDir `"$InstallDir`""
}

# --- resident mitmdump task (auto-restart, starts at logon) ---
# Stop any previous instance first so re-running setup never fights over port.
# Filter by command line so the user's OWN unrelated mitmproxy/mitmdump
# sessions (e.g. an active capture) are never killed.
Stop-ScheduledTask -TaskName 'zcode-shield-mitm' -ErrorAction SilentlyContinue
Get-CimInstance Win32_Process -Filter "Name='mitmdump.exe'" -ErrorAction SilentlyContinue |
  Where-Object { $_.CommandLine -like '*zcode-shield*' } |
  ForEach-Object { Stop-Process -Id $_.ProcessId -Force -ErrorAction SilentlyContinue }
$mitTrigger = New-ScheduledTaskTrigger -AtLogOn -User $env:USERNAME
# Delay the logon trigger: firing at the exact logon instant races session
# setup, and a canceled child CreateProcess (0x800704C7) is precisely that
# failure mode. 30s in, the interactive session is ready; the launcher's own
# retry loop covers any residual flakiness.
$mitTrigger.Delay = 'PT30S'
$mitSettings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries `
  -RestartCount 999 -RestartInterval (New-TimeSpan -Minutes 1) -ExecutionTimeLimit (New-TimeSpan -Days 3650)
Register-ScheduledTask -TaskName 'zcode-shield-mitm' -Action $mitAction -Trigger $mitTrigger `
  -Settings $mitSettings -Force | Out-Null
Start-ScheduledTask -TaskName 'zcode-shield-mitm'
Write-Host "[*] mitmdump task started (127.0.0.1:$ProxyPort)"

# --- monitor task every 30s ---
# Task Scheduler's minimum repetition interval is 1 minute, so two 1-minute
# triggers offset by 30s are used to get an effective 30s cadence.
$watchTrigger = @(
  New-ScheduledTaskTrigger -Once -At (Get-Date) -RepetitionInterval (New-TimeSpan -Minutes 1) -RepetitionDuration (New-TimeSpan -Days 3650)
  New-ScheduledTaskTrigger -Once -At ((Get-Date).AddSeconds(30)) -RepetitionInterval (New-TimeSpan -Minutes 1) -RepetitionDuration (New-TimeSpan -Days 3650)
)
$watchSettings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries `
  -MultipleInstances IgnoreNew -ExecutionTimeLimit (New-TimeSpan -Minutes 5)
Register-ScheduledTask -TaskName 'zcode-snapshot-watch' -Action $watchAction -Trigger $watchTrigger `
  -Settings $watchSettings -Force | Out-Null
Write-Host "[*] monitor task registered (every 30s)"

# --- wait for the CA cert and the listening port, then print instructions ---
function Test-LocalPort([int]$Port) {
  $client = New-Object Net.Sockets.TcpClient
  try {
    $async = $client.BeginConnect('127.0.0.1', $Port, $null, $null)
    if ($async.AsyncWaitHandle.WaitOne(300)) { $client.EndConnect($async); return $true }
    return $false
  } catch { return $false } finally { $client.Close() }
}

$ca = Join-Path $env:USERPROFILE '.mitmproxy\mitmproxy-ca-cert.pem'
$deadline = (Get-Date).AddSeconds(20)
while (-not ((Test-Path $ca) -and (Test-LocalPort $ProxyPort)) -and (Get-Date) -lt $deadline) {
  Start-Sleep -Milliseconds 500
}

Write-Host ""
if (Test-Path $ca) {
  # End-to-end self-test: prove the addon answers 403 before telling the user
  # it is safe to point ZCode at the proxy. Needs network; skipped silently
  # (with a note) if curl.exe is unavailable or offline.
  $curl = Get-Command curl.exe -ErrorAction SilentlyContinue
  if ($curl) {
    $code = & $curl.Source -sS --ssl-no-revoke -x "http://127.0.0.1:$ProxyPort" --cacert $ca `
      -o NUL -w "%{http_code}" "https://zcode.z.ai/api/v1/snapshot/upload-credential" 2>$null
    if ("$code" -eq '403') { Write-Host "[*] self-test OK: snapshot endpoint answered 403 (blocked)" }
    else { Write-Warning "self-test unexpected result: '$code' (expected 403) - check $InstallDir\mitmdump.log before enabling" }
  }
  Write-Host "==== 启用拦截: 完全退出 ZCode 后, 运行以下命令, 然后启动 ZCode ===="
  Write-Host "  powershell -NoProfile -ExecutionPolicy Bypass -File `"$InstallDir\enable-proxy.ps1`" -ProxyPort $ProxyPort"
  Write-Host "==== 恢复直连: 完全退出 ZCode 后运行 disable-proxy.ps1 并重启 ZCode ===="
  Write-Host ""
  Write-Host "验证: curl.exe --ssl-no-revoke -x http://127.0.0.1:$ProxyPort --cacert `"$ca`" -o NUL -w `"%{http_code}`" https://zcode.z.ai/api/v1/snapshot/upload-credential  (expect 403)"
} else {
  Write-Warning "CA cert not generated yet at $ca - check: Get-ScheduledTask zcode-shield-mitm; $InstallDir\mitmdump.log"
}
